# The variable we are attempting to predict (sale price)
target: Outcome

# feautes
features:
  - Time
  - P1
  - P2
  - P3
  - P4
  - P5
  - P6
  - P7
  - P8
  - P9
  - P10
  - P11
  - P12
  - P13
  - P14
  - P15
  - P16
  - P17
  - P18
  - P19
  - P20
  - P21
  - P22
  - P23
  - P24
  - P25
  - P26
  - P27
  - P28
  - Dollar_amount

# set train/test split
test_size: 0.2

# variables with missing value in the train set
VARS_WITH_MISSING:
  - Dollar_amount

# variables that need to scale
SCALED_VARS:
  - Dollar_amount
  - Time